"""empty message

Revision ID: 4d67e2358cc1
Revises: d33aa4c5fdf1
Create Date: 2019-09-10 00:27:15.065164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d67e2358cc1'
down_revision = 'd33aa4c5fdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicoms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('pathFile', sa.String(length=255), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('fileID', sa.String(length=255), nullable=False),
    sa.Column('nframe', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('deviceID', sa.String(length=50), nullable=True),
    sa.Column('lad', sa.Boolean(), nullable=True),
    sa.Column('lcx', sa.Boolean(), nullable=True),
    sa.Column('rca', sa.Boolean(), nullable=True),
    sa.Column('isNotStandardImage', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dicoms')
    # ### end Alembic commands ###
