"""empty message

Revision ID: d33aa4c5fdf1
Revises: 
Create Date: 2019-09-10 00:25:57.934074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33aa4c5fdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('fullname', sa.String(
                        length=100, collation='utf8mb4_general_ci'), nullable=False),
                    sa.Column('phone', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(
                        length=255), nullable=False),
                    sa.Column('deviceID', sa.String(length=50), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('job', sa.String(
                        length=255, collation='utf8mb4_general_ci'), nullable=True),
                    sa.Column('department', sa.String(
                        length=255, collation='utf8mb4_general_ci'), nullable=True),
                    sa.Column('organization', sa.String(
                        length=255, collation='utf8mb4_general_ci'), nullable=True),
                    sa.Column('address', sa.String(
                        length=255, collation='utf8mb4_general_ci'), nullable=True),
                    sa.Column('activate', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('fullname'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
